apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: your-angular-app:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-volume
          mountPath: /etc/secrets
          readOnly: true
        command: ["/bin/sh", "-c"]
        args:
        - "node /app/scripts/watch-config.js & nginx -g 'daemon off;'"
      volumes:
      - name: secrets-volume
        secret:
          secretName: app-secrets