apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # These values are base64 encoded
  api-url: aHR0cHM6Ly9hcGkuZXhhbXBsZS5jb20= # https://api.example.com
  auth-token: c2VjcmV0LXRva2VuLTEyMzQ= # secret-token-1234